### ISSUE TITLE
PHP Warning in index.php im Webroot

### ISSUE THREAD

**Issue by Samson1964** [contao/core#6739]
```
[15-Feb-2014 13:41:32 Europe/Berlin] 
PHP Warning: current() expects parameter 1 to be array, null given in /kunden/107305_14053/webseiten/schachbund.2014/index.php on line 120
#0 [internal function]: __error(2, 'current() expec...', '/kunden/107305_...', 120, Array)
#1 /kunden/107305_14053/webseiten/schachbund.2014/index.php(120): current(NULL)
#2 /kunden/107305_14053/webseiten/schachbund.2014/index.php(407): Index->run()
#3 {main} 
```
Taucht immer mal wieder den ganzen Tag über in meinem Error.log auf.

**Comment by leofeyer** [comment]
Behoben in 670822ce82a72a8d654e37106ec0e0b5f7d68e48.
