### ISSUE TITLE
[3.4.0] event list parameter month: wrong format = Fatal error

### ISSUE THREAD

**Issue by mathContao** [contao/core#7545]
On a page with event list modul you can use ?month parameter. Format: YYYYMM.

If you change manually f.e. to MMYYYY a Fatal error occurs.

See at demo page:
http://demo.contao.org/en/events.html?month=052015 

settings: displayErrors = true

```
Fatal error: Uncaught exception OutOfBoundsException with message Invalid date "052015" thrown in path\_core-3.4.0\system\modules\core\library\Contao\Date.php on line 438

#0 path\_core-3.4.0\system\modules\core\library\Contao\Date.php(71): Contao\Date->dateToUnix()
#1 path\_core-3.4.0\system\modules\calendar\modules\ModuleCalendar.php(97): Contao\Date->__construct('052015', 'Ym')
#2 path\_core-3.4.0\system\modules\core\modules\Module.php(163): Contao\ModuleCalendar->compile()
#3 path\_core-3.4.0\system\modules\calendar\modules\ModuleCalendar.php(85): Contao\Module->generate()
#4 path\_core-3.4.0\system\modules\core\elements\ContentModule.php(65): Contao\ModuleCalendar->generate()
#5 path\_core-3.4.0\system\modules\core\library\Contao\Controller.php(473): Contao\ContentModule->generate()
#6 path\_core-3.4.0\system\modules\core\modules\ModuleArticle.php(196): Contao\Controller::getContentElement(Object(Contao\ContentModel), 'left')
#7 path\_core-3.4.0\system\modules\core\modules\Module.php(163): Contao\ModuleArticle->compile()
#8 path\_core-3.4.0\system\modules\core\modules\ModuleArticle.php(59): Contao\Module->generate()
#9 path\_core-3.4.0\system\modules\core\library\Contao\Controller.php(409): Contao\ModuleArticle->generate(false)
#10 path\_core-3.4.0\system\modules\core\library\Contao\Controller.php(273): Contao\Controller::getArticle(Object(Contao\ArticleModel), false, false, 'left')
#11 path\_core-3.4.0\system\modules\core\pages\PageRegular.php(138): Contao\Controller::getFrontendModule('0', 'left')
#12 path\_core-3.4.0\system\modules\core\controllers\FrontendIndex.php(253): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#13 path\_core-3.4.0\index.php(22): Contao\FrontendIndex->run()
#14 {main}
```

(in my opinion) wrong format/value should ignored instead throwing an error.

**Comment by Toflar** [comment]
+1

**Comment by leofeyer** [comment]
Really? Why should we care if someone manually messes with the query parameters? Contao will throw exceptions at a lot of other places as well if you manipulate user data.

**Comment by aschempp** [comment]
I think exceptions should always be handled. Possibly render a 404 because that month does not exist?

**Comment by discordier** [comment]
I agree toally with @aschempp on this one and think that 404 should be the way to go.

**Comment by leofeyer** [comment]
As discussed on Mumble on January 29th, we want to show the 404 page in this case. We also want to change this behavior globally (see #7238).

**Comment by leofeyer** [comment]
Changed in 55319dfe0cb064a39f1fc0420538fe7f6516c2ca.

@aschempp @discordier We definitely need a response exception or something alike in Contao 4 to handle these cases. It will be impossible to return the page objects back to the controller.
