### ISSUE TITLE
Problem with Contao 3.4.2

### ISSUE THREAD

**Issue by Sanderadio** [contao/core#7593]
Hi,

After copying all files (Live Update doesn't work with my hosting provider) version 3.4.2 seems to work okay, but the install.php gives the errors below. What could be wrong? (For security reasons in this error log I changed the real path to /path/to/).

Thank you!
Sander

```
Notice: Undefined index: BE_DATA in /path/to/system/modules/core/library/Contao/Session.php on line 52 Notice: Undefined index: HTTP_X_FORWARDED_HOST in /path/to/system/modules/core/library/Contao/Environment.php on line 302 Notice: Undefined index: SSL_SESSION_ID in /path/to/system/modules/core/library/Contao/Environment.php on line 313 Notice: Undefined index: HTTPS in /path/to/system/modules/core/library/Contao/Environment.php on line 313 Notice: Undefined index: HTTPS in /path/to/system/modules/core/library/Contao/Environment.php on line 313 
Warning: Cannot modify header information - headers already sent by (output started at /path/to/system/modules/core/library/Contao/Session.php:52) in system/modules/core/library/Contao/Template.php on line 255
#0 [internal function]: __error(2, 'Cannot modify h...', '/customers/3/d/...', 255, Array)
#1 system/modules/core/library/Contao/Template.php(255): header('Vary: User-Agen...', false)
#2 system/modules/core/classes/BackendTemplate.php(113): Contao\Template->output()
#3 system/modules/core/controllers/BackendInstall.php(864): Contao\BackendTemplate->output()
#4 system/modules/core/controllers/BackendInstall.php(99): Contao\BackendInstall->outputAndExit()
#5 contao/install.php(24): Contao\BackendInstall->run()
#6 {main}

Warning: Cannot modify header information - headers already sent by (output started at /path/to/system/modules/core/library/Contao/Session.php:52) in system/modules/core/library/Contao/Template.php on line 256
#0 [internal function]: __error(2, 'Cannot modify h...', '/customers/3/d/...', 256, Array)
#1 system/modules/core/library/Contao/Template.php(256): header('Content-Type: t...')
#2 system/modules/core/classes/BackendTemplate.php(113): Contao\Template->output()
#3 system/modules/core/controllers/BackendInstall.php(864): Contao\BackendTemplate->output()
#4 system/modules/core/controllers/BackendInstall.php(99): Contao\BackendInstall->outputAndExit()
#5 contao/install.php(24): Contao\BackendInstall->run()
#6 {main}
```

**Comment by minstyle** [comment]
I have the same problem.

**Comment by Doose** [comment]
Mee too

**Comment by leofeyer** [comment]
What is your `error_reporting` setting in your `php.ini`?

**Comment by Znrl** [comment]
Ist das gleiche auf:
http://demo.contao.org/contao/install.php

```
Notice: Undefined index: HTTP_X_FORWARDED_HOST in /home/www/demo/system/modules/core/library/Contao/Environment.php on line 302

Notice: Undefined index: SSL_SESSION_ID in /home/www/demo/system/modules/core/library/Contao/Environment.php on line 313

Notice: Undefined index: HTTPS in /home/www/demo/system/modules/core/library/Contao/Environment.php on line 313

Notice: Undefined index: HTTPS in /home/www/demo/system/modules/core/library/Contao/Environment.php on line 313

Warning: Cannot modify header information - headers already sent by (output started at /home/www/demo/system/modules/core/library/Contao/Environment.php:302) in system/modules/core/library/Contao/Template.php on line 255

#0 [internal function]: __error(2, 'Cannot modify h...', '...', 255, Array)
#1 system/modules/core/library/Contao/Template.php(255): header('Vary: User-Agen...', false)
#2 system/modules/core/classes/BackendTemplate.php(113): Contao\Template->output()
#3 system/modules/core/controllers/BackendInstall.php(864): Contao\BackendTemplate->output()
#4 system/modules/core/controllers/BackendInstall.php(99): Contao\BackendInstall->outputAndExit()
#5 contao/install.php(24): Contao\BackendInstall->run()
#6 {main}


Warning: Cannot modify header information - headers already sent by (output started at /home/www/demo/system/modules/core/library/Contao/Environment.php:302) in system/modules/core/library/Contao/Template.php on line 256

#0 [internal function]: __error(2, 'Cannot modify h...', '...', 256, Array)
#1 system/modules/core/library/Contao/Template.php(256): header('Content-Type: t...')
#2 system/modules/core/classes/BackendTemplate.php(113): Contao\Template->output()
#3 system/modules/core/controllers/BackendInstall.php(864): Contao\BackendTemplate->output()
#4 system/modules/core/controllers/BackendInstall.php(99): Contao\BackendInstall->outputAndExit()
#5 contao/install.php(24): Contao\BackendInstall->run()
#6 {main}
```

Wenn man die alte system/initialize.php nimmt sind die Meldungen weg.
Da wurde ja was bzgl. performance geschraubt.

**Comment by planepix** [comment]
Hi,

i updated a 3.4.0 installation to 3.4.2 via LiveUpdate.
Update runs well, BE and FE is working fine.

So i checked the installer and get these errors:
Notice: Undefined index: HTTP_X_FORWARDED_HOST in /www/htdocs/w012be67/domain/system/modules/core/library/Contao/Environment.php on line 302

Notice: Undefined index: SSL_SESSION_ID in /www/htdocs/w012be67/domain/system/modules/core/library/Contao/Environment.php on line 313

Notice: Undefined index: HTTPS in /www/htdocs/w012be67/domain/system/modules/core/library/Contao/Environment.php on line 313

Notice: Undefined index: HTTPS in /www/htdocs/w012be67/domain/system/modules/core/library/Contao/Environment.php on line 313

System data:
Hoster: allinkl
PHP: 5.4 als Fast-CGI

**Comment by Sanderadio** [comment]
@leofeyer My local and master value is 24567.

**Comment by leofeyer** [comment]
Fixed in 2ab1fd3618ba4f1b12179945c4b5a964cd9f1bbf.

**Comment by Sanderadio** [comment]
@leofeyer Thanks for the quick hotfix!

**Comment by Tastaturberuf** [comment]
Bitte auf die Webseite damit, das ist keine Kleinigkeit.

**Comment by BugBuster1701** [comment]
Raus mit dem Release. Neue Nutzer von Contao die gleich beim Install ne Fehlermeldung bekommen, gehen gleich wieder.

**Comment by leofeyer** [comment]
Immer mit der Ruhe. Wir haben 7 Tickets mit dem Status "up for discussion" offen. Lasst uns diese erstmal beim Call gleich besprechen und sehen, ob und wie wir diese lösen. Dann können wir Anfang nächster Woche ein vernünftiges Release machen, das nicht nur eine geänderte Code-Zeile enthält :)

**Comment by Tastaturberuf** [comment]
Ich persönlich sehe das als dringend an. Nen fehlerhafter Installer geht gar nicht.

**Comment by Znrl** [comment]
Naja hier wird ja auch keiner der "Fehler" gelöst. Sie werden nur ausgeblendet (sind auch nur Warnings und Notices). Befolgt man die Tipps bzgl. installer.php und löscht sie, benennt sie um o.ä. ist es auch nicht weiter tragisch. Das argument von BugBuster ist aber durchaus richtig, zu viel Zeit sollte man nicht vergehen lassen.

**Comment by Tastaturberuf** [comment]
Es geht nicht um uns, wir lesen ja hier.

**Comment by ofriedrich** [comment]
Das sind nur Warnings... meine Güte. Macht Euch nicht verrückt. Einfach ein isset() mit in die Abfragen und gut ist. Ich kenne php-Anwendungen, die ohne Abschalten sämtlicher Error-Reports überhaupt nicht funktionieren...

**Comment by Sanderadio** [comment]
@ofriedrich Nein, das ist falsch. Es sind nicht nur Warnings. `install.php` wasn't working without the hotfix @leofeyer offered a week ago.

**Comment by xantippe** [comment]
dachte die Sache wäre gefixt... gerade per Live-Update ein update gemacht... nun kommt

```
Notice: Undefined index: requires in /is/htdocs/xyz/www/contao/system/modules/core/library/Contao/ModuleLoader.php on line 149

Notice: Undefined index: requires in /is/htdocs/xyz/www/contao/system/modules/core/library/Contao/ModuleLoader.php on line 149

Notice: Undefined index: requires in /is/htdocs/xyz/www/contao/system/modules/core/library/Contao/ModuleLoader.php on line 149

Notice: Undefined index: requires in /is/htdocs/xyz/www/contao/system/modules/core/library/Contao/ModuleLoader.php on line 149

Notice: Undefined index: HTTP_X_FORWARDED_HOST in /is/htdocs/xyz/www/contao/system/modules/core/library/Contao/Environment.php on line 302

Notice: Undefined index: SSL_SESSION_ID in /is/htdocs/xyz/www/contao/system/modules/core/library/Contao/Environment.php on line 313

Notice: Undefined index: HTTPS in /is/htdocs/xyz/www/contao/system/modules/core/library/Contao/Environment.php on line 313

Notice: Undefined index: HTTPS in /is/htdocs/xyz/www/contao/system/modules/core/library/Contao/Environment.php on line 313

Notice: Undefined index: dataContainer in /is/htdocs/xyz/www/contao/system/modules/core/library/Contao/DcaExtractor.php on line 349

Notice: Undefined index: group in /is/htdocs/xyz/www/contao/system/modules/core/library/Contao/Model/QueryBuilder.php on line 75

Notice: Undefined index: having in /is/htdocs/xyz/www/contao/system/modules/core/library/Contao/Model/QueryBuilder.php on line 81

Notice: Undefined index: order in /is/htdocs/xyz/www/contao/system/modules/core/library/Contao/Model/QueryBuilder.php on line 87

Warning: Cannot modify header information - headers already sent by (output started at /is/htdocs/xyz/www/contao/system/modules/core/library/Contao/ModuleLoader.php:149) in system/modules/core/library/Contao/System.php on line 559
...
```

und nu?

**Comment by BugBuster1701** [comment]
Gerade in 3.5.0-RC1, Update eine Erweiterung mit Paketverwaltung:
```
PHP Notice: Undefined index: precision in /web/system/modules/core/library/Contao/Database/Installer.php on line 453
PHP Notice: Undefined index: length in /web/system/modules/core/library/Contao/Database/Installer.php on line 451
PHP Notice: Undefined index: ORIG_SCRIPT_NAME in /web/system/modules/core/library/Contao/Environment.php on line 102
PHP Notice: Undefined index: dataContainer in /web/system/modules/core/library/Contao/DcaExtractor.php on line 386
PHP Notice: Undefined index: ALTER_ADD in /web/system/modules/core/library/Contao/Database/Installer.php on line 184
```
und viele viele weitere bzw. Wiederholungen derselben.
Es wird allerdings gleich ein redirect eingeleitet (DB Aktualisierung), sodass man die Meldungen kaum sieht.
```error_reporting: 22519 (E_ALL & ~E_NOTICE & ~E_STRICT & ~E_DEPRECATED)```

Bei einer Erstinstallation kamen die Meldungen jedoch nicht.

**Comment by aschempp** [comment]
Das ist ein Problem der Composer-Erweiterung, welche ich schon vor Monaten gemeldet habe…

**Comment by glasen** [comment]
Siehe Kommentar von xantippe:

Der gleiche Fehler kommt bei mir, wenn ich versuche 3.4.5 in einem Webpack L von Hosteurope zu installieren. Auf einem lokalen Server (Ubuntu 14.04) funktioniert die Installation von 3.4.5 sowie ein Upgrade von 3.3.7 völlig problemlos.
