### ISSUE TITLE
[3.5.0 RC] file manage broken on xampp

### ISSUE THREAD

**Issue by Zeromax** [contao/core#7847]
On Windows the file Manager is broken.

https://github.com/contao/core/blob/1434b1a3559d61f45bc2d4e52df38cb847f2c5c4/system/modules/core/drivers/DC_Folder.php#L2303
````php
$currentFolder = str_replace(TL_ROOT . DIRECTORY_SEPARATOR, '', $folders[$f]);
```

This will not work, cause the first slash from a file is not a backslash.
`$folders[$f]` = `D:\www\contao-core/files/tiny_templates`
`TL_ROOT . DIRECTORY_SEPARATOR` = `D:\www\contao-core\`

I think there should be a path normalization. In the `File.php` all path in this Clas are returned with a slash and not normalized for the correct `DIRECTORY_SEPARATOR`.

```
Warning: filesize(): stat failed for D:\www\contao-core/D:\www\contao-core/files/IMG_1275.jpg in system\modules\core\library\Contao\File.php on line 184 #0 [internal function]: __error(2, 'filesize(): sta...', 'D:\\www\\contao-c...', 184, Array)
#1 system\modules\core\library\Contao\File.php(184): filesize('D:\\www\\contao-c...')
#2 system\modules\core\drivers\DC_Folder.php(2406): Contao\File->__get('filesize')
#3 system\modules\core\drivers\DC_Folder.php(308): Contao\DC_Folder->generateTree('D:\\www\\contao-c...', 0, false, false, false)
#4 system\modules\core\classes\Backend.php(639): Contao\DC_Folder->showAll()
#5 system\modules\core\controllers\BackendMain.php(131): Contao\Backend->getBackendModule('files')
#6 contao\main.php(20): Contao\BackendMain->run()
#7 {main}


Warning: filesize(): stat failed for D:\www\contao-core/D:\www\contao-core/files/P1140966_back 4zu3.JPG in system\modules\core\library\Contao\File.php on line 184 #0 [internal function]: __error(2, 'filesize(): sta...', 'D:\\www\\contao-c...', 184, Array)
#1 system\modules\core\library\Contao\File.php(184): filesize('D:\\www\\contao-c...')
#2 system\modules\core\drivers\DC_Folder.php(2406): Contao\File->__get('filesize')
#3 system\modules\core\drivers\DC_Folder.php(308): Contao\DC_Folder->generateTree('D:\\www\\contao-c...', 0, false, false, false)
#4 system\modules\core\classes\Backend.php(639): Contao\DC_Folder->showAll()
#5 system\modules\core\controllers\BackendMain.php(131): Contao\Backend->getBackendModule('files')
#6 contao\main.php(20): Contao\BackendMain->run()
#7 {main}


Warning: filesize(): stat failed for D:\www\contao-core/D:\www\contao-core/files/tinymce.css in system\modules\core\library\Contao\File.php on line 184 #0 [internal function]: __error(2, 'filesize(): sta...', 'D:\\www\\contao-c...', 184, Array)
#1 system\modules\core\library\Contao\File.php(184): filesize('D:\\www\\contao-c...')
#2 system\modules\core\drivers\DC_Folder.php(2406): Contao\File->__get('filesize')
#3 system\modules\core\drivers\DC_Folder.php(308): Contao\DC_Folder->generateTree('D:\\www\\contao-c...', 0, false, false, false)
#4 system\modules\core\classes\Backend.php(639): Contao\DC_Folder->showAll()
#5 system\modules\core\controllers\BackendMain.php(131): Contao\Backend->getBackendModule('files')
#6 contao\main.php(20): Contao\BackendMain->run()
#7 {main}
```

**Comment by leofeyer** [comment]
Fixed in eb131dbe5a168b5675a1d4a8db2e06e6b2d911ee. Can you please checkout the latest `release/4.0.0` branch and check if it works for you?

**Comment by Zeromax** [comment]
@leofeyer Yes on the way...

**Comment by Zeromax** [comment]
@leofeyer I will put the issue reports to the contao/standard-edition

**Comment by leofeyer** [comment]
Why? The ticket is assigned to Contao 3.5!

**Comment by Zeromax** [comment]
ah... You have written

> Can you please checkout the latest  `release/4.0.0`  branch and check if it works for you?

Will check 3.5 now ;)

**Comment by leofeyer** [comment]
My bad :(

**Comment by Zeromax** [comment]
No Problem ;) You have to manage lots of branches at the Moment.

So I checked out: `release/3.5.0` and everything works fine.

Btw: The part overlay is not added yet?

**Comment by leofeyer** [comment]
The part overlay?

**Comment by Zeromax** [comment]
When I hove the Image in the file tree, then it swaps -> https://github.com/contao/core/pull/7814

**Comment by leofeyer** [comment]
Nope, haven't got any feedback of one of the other core developers yet.

**Comment by Zeromax** [comment]
Ah ok. Thanks for the info.
