### ISSUE TITLE
[3.5.0]Error when restoring a version

### ISSUE THREAD

**Issue by tabcontao** [contao/core#7869]
Contao Version: 3.5.0
PHP-Version: 5.5.24

When I try to restore an older version of a text element, I get the following error in system/logs/error.log:
```
[07-Jun-2015 22:23:35 Europe/Berlin] PHP Fatal error: Uncaught exception 'Exception' with message 'Query error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'PRIMARY='', pid_ptable_invisible_sorting='' WHERE id='203'' at line 1 (UPDATE tl_content SET id='203', pid='49', ptable='tl_article', sorting='96', tstamp='1430825610', type='text', headline='a:2:{s:4:\"unit\";s:2:\"h1\";s:5:\"value\";s:0:\"\";}', text='<p>... original text deleted ...</p>', addImage='', singleSRC=NULL, alt='', title='', size='', imagemargin='', imageUrl='', fullsize='', caption='', floating='above', html=NULL, listtype='', listitems=NULL, tableitems=NULL, summary='', thead='', tfoot='', tleft='', sortable='', sortIndex='0', sortOrder='ascending', mooHeadline='', mooStyle='', mooClasses='', highlight='', shClass='', code=NULL, url='', target='', titleText='', linkTitle='', embed='', rel='', useImage='', multiSRC=NULL, orderSRC=NULL, useHomeDir='', perRow='4', perPage='0', numberOfItems='0', sortBy='', galleryTpl='', playerSRC=NULL, youtube='', posterSRC=NULL, playerSize='', autoplay='', cteAlias='0', articleAlias='0', article='0', form='0', module='0', protected='', groups=NULL, guests='', cssID='a:2:{i:0;s:0:\"\";i:1;s:10:\"akmw_neues\";}', space='a:2:{i:0;s:0:\"\";i:1;s:0:\"\";}', invisible='', start='', stop='', sliderDelay='0', sliderSpeed='300', sliderStartSlide='0', sliderContinuous='', metaIgnore='', customTpl='', PRIMARY='', pid_ptable_invisible_sorting='' WHERE id='203')' thrown in /homepages/27/d210594196/htdocs/AKMW_3_5_0/system/modules/core/library/Contao/Database/Statement.php on line 295
#0 /homepages/27/d210594196/htdocs/AKMW_3_5_0/system/modules/core/library/Contao/Database/Statement.php(264): Contao\Database\Statement->query()
#1 /homepages/27/d210594196/htdocs/AKMW_3_5_0/system/modules/core/classes/Versions.php(269): Contao\Database\Statement->execute('203')
#2 /homepages/27/d210594196/htdocs/AKMW_3_5_0/system/modules/core/drivers/DC_Table.php(1769): Contao\Versions->restore('1')
#3 /homepages/27/d210594196/htdocs/AKMW_3_5_0/system/modules/core/classes/Backend.php(639): Contao\DC_Table->edit()
#4 /homepages/27/d210594196/htdocs/AKMW_3_5_0/system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('article')
#5 /homepages/27/d210594196/htdocs/AKMW_3_5_0/contao/main.php(20): Contao\BackendMain->run()
#6 {main}

```
See also the following Thread in the Conto community forum:
https://community.contao.org/de/showthread.php?57499-3-4-5-gt-3-5-0-Ver%E4nderte-Systemvoraussetzung

Reproduction in demo is not possible, because the demo is still 3.4 and restoring versions works in 3.4.x.

**Comment by BugBuster1701** [comment]
I can confirm that. Problem is the table field PRIMARY, the generated SQL statement is incorrect.
```
Fatal error: Uncaught exception Exception with message Query error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'PRIMARY='', pid_ptable_invisible_sorting='' WHERE id='341'' at line 1 (UPDATE tl_content SET id='341', pid='97', ptable='tl_article', sorting='128', tstamp='1433711208', type='text', headline='a:2:{s:4:\"unit\";s:2:\"h1\";s:5:\"value\";s:6:\"test 1\";}', text='

test1
', addImage='', singleSRC=NULL, alt='', title='', size='', imagemargin='', imageUrl='', fullsize='', caption='', floating='above', html=NULL, listtype='', listitems=NULL, tableitems=NULL, summary='', thead='', tfoot='', tleft='', sortable='', sortIndex='0', sortOrder='ascending', mooHeadline='', mooStyle='', mooClasses='', highlight='', shClass='', code=NULL, url='', target='', titleText='', linkTitle='', embed='', rel='', useImage='', multiSRC=NULL, orderSRC=NULL, useHomeDir='', perRow='4', perPage='0', numberOfItems='0', sortBy='', metaIgnore='', galleryTpl='', customTpl='', playerSRC=NULL, youtube='', posterSRC=NULL, playerSize='', autoplay='', sliderDelay='0', sliderSpeed='300', sliderStartSlide='0', sliderContinuous='', cteAlias='0', articleAlias='0', article='0', form='0', module='0', protected='', groups=NULL, guests='', cssID='a:2:{i:0;s:0:\"\";i:1;s:0:\"\";}', space='a:2:{i:0;s:0:\"\";i:1;s:0:\"\";}', invisible='', start='', stop='', com_order='ascending', com_perPage='0', com_moderate='', com_bbcode='', com_disableCaptcha='', com_requireLogin='', com_template='com_default', PRIMARY='', pid_ptable_invisible_sorting='' WHERE id='341') thrown in system/modules/core/library/Contao/Database/Statement.php on line 295

#0 system/modules/core/library/Contao/Database/Statement.php(264): Contao\Database\Statement->query()
#1 system/modules/core/classes/Versions.php(269): Contao\Database\Statement->execute('341')
#2 system/modules/core/drivers/DC_Table.php(1769): Contao\Versions->restore('1')
#3 system/modules/core/classes/Backend.php(639): Contao\DC_Table->edit()
#4 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('article')
#5 contao/main.php(20): Contao\BackendMain->run()
#6 {main}
```

**Comment by Nico0o** [comment]
I can confirm that too.

**Comment by leofeyer** [comment]
I assume the issue has been introduced in #7755. @aschempp /cc

**Comment by aschempp** [comment]
Probably, but why would `Database::getFieldnames()` return a field called `PRIMARY` (which probably is the key) ?

**Comment by tabcontao** [comment]
If it helps any, the last two listed "fields" in the created UPDATE-Statement, "PRIMARY" and "pid_ptable_invisible_sorting", are the last two indizes of the table tl_content. But I guess you knew that already ;)

**Comment by leofeyer** [comment]
Fixed in 0fdcc8e36999f7eb5036b761276222d33c185ffe.

**Comment by BugBuster1701** [comment]
:+1:

**Comment by KlausGrenoble** [comment]
très bien.
Merci
