### ISSUE TITLE
[3.5.0] PHP Warning ModulePassword.php

### ISSUE THREAD

**Issue by Mynyx** [contao/core#7896]
````
[23-Jun-2015 15:10:51 Europe/Berlin] 
PHP Warning: array_pop() expects parameter 1 to be array, null given in /www/htdocs/xxx/system/modules/core/modules/ModulePassword.php on line 225
#0 [internal function]: __error(2, 'array_pop() exp...', '/www/htdocs/xxx...', 225, Array)
#1 /www/htdocs/xxx/system/modules/core/modules/ModulePassword.php(225): array_pop(NULL)
#2 /www/htdocs/xxx/system/modules/core/modules/ModulePassword.php(70): Contao\ModulePassword->setNewPassword()
#3 /www/htdocs/xxx/system/modules/core/modules/Module.php(282): Contao\ModulePassword->compile()
#4 /www/htdocs/xxx/system/modules/core/modules/ModulePassword.php(50): Contao\Module->generate()
#5 /www/htdocs/xxx/system/modules/core/elements/ContentModule.php(59): Contao\ModulePassword->generate()
#6 /www/htdocs/xxx/system/modules/core/library/Contao/Controller.php(476): Contao\ContentModule->generate()
#7 /www/htdocs/xxx/system/modules/core/modules/ModuleArticle.php(213): Contao\Controller::getContentElement(Object(Contao\ContentModel), 'main')
#8 /www/htdocs/xxx/system/modules/core/modules/Module.php(282): Contao\ModuleArticle->compile()
#9 /www/htdocs/xxx/system/modules/core/modules/ModuleArticle.php(67): Contao\Module->generate()
#10 /www/htdocs/xxx/system/modules/core/library/Contao/Controller.php(409): Contao\ModuleArticle->generate(false)
#11 /www/htdocs/xxx/system/modules/core/library/Contao/Controller.php(269): Contao\Controller::getArticle(Object(Contao\ArticleModel), false, false, 'main')
#12 /www/htdocs/xxx/system/modules/core/pages/PageRegular.php(133): Contao\Controller::getFrontendModule('0', 'main')
#13 /www/htdocs/xxx/system/modules/core/controllers/FrontendIndex.php(267): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#14 /www/htdocs/xxx/index.php(20): Contao\FrontendIndex->run()
#15 {main}
````

**Comment by leofeyer** [comment]
Fixed in d01d94fca33b7582b26c861722aeb2abd72e5f86.
