### ISSUE TITLE
[3.5.2] PHP-Warning when using "show differences" in BE start page

### ISSUE THREAD

**Issue by tabcontao** [contao/core#7971]
I added an external style sheet in a page layout, which didn't use any external style sheets before. Then I clicked on "show differences" in BE start page. As a result, I got the following PHP warnings in the error.log.

```
[16-Aug-2015 23:45:10 Europe/Berlin] 
PHP Warning: unpack(): Type H: not enough input, need 4, have 0 in /homepages/xx/xxxxxxxxxx/htdocs/xxxxxxxxx-v3_5_2/system/modules/core/library/Contao/StringUtil.php on line 567
#0 [internal function]: __error(2, 'unpack(): Type ...', '/homepages/xx/x...', 567, Array)
#1 /homepages/xx/xxxxxxxxxx/htdocs/xxxxxxxxx-v3_5_2/system/modules/core/library/Contao/StringUtil.php(567): unpack('H8time_low/H4ti...', '')
#2 [internal function]: Contao\StringUtil::binToUuid('')
#3 /homepages/xx/xxxxxxxxxx/htdocs/xxxxxxxxx-v3_5_2/system/modules/core/classes/Versions.php(689): array_map('StringUtil::bin...', Array)
#4 /homepages/xx/xxxxxxxxxx/htdocs/xxxxxxxxx-v3_5_2/system/modules/core/classes/Versions.php(404): Contao\Versions->implodeRecursive(Array, true)
#5 /homepages/xx/xxxxxxxxxx/htdocs/xxxxxxxxx-v3_5_2/system/modules/core/drivers/DC_Table.php(1763): Contao\Versions->compare()
#6 /homepages/xx/xxxxxxxxxx/htdocs/xxxxxxxxx-v3_5_2/system/modules/core/classes/Backend.php(639): Contao\DC_Table->edit()
#7 /homepages/xx/xxxxxxxxxx/htdocs/xxxxxxxxx-v3_5_2/system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('themes')
#8 /homepages/xx/xxxxxxxxxx/htdocs/xxxxxxxxx-v3_5_2/contao/main.php(20): Contao\BackendMain->run()
#9 {main}

[16-Aug-2015 23:45:10 Europe/Berlin] 
PHP Warning: implode(): Invalid arguments passed in /homepages/xx/xxxxxxxxxx/htdocs/xxxxxxxxx-v3_5_2/system/modules/core/library/Contao/StringUtil.php on line 567
#0 [internal function]: __error(2, 'implode(): Inva...', '/homepages/xx/x...', 567, Array)
#1 /homepages/xx/xxxxxxxxxx/htdocs/xxxxxxxxx-v3_5_2/system/modules/core/library/Contao/StringUtil.php(567): implode('-', false)
#2 [internal function]: Contao\StringUtil::binToUuid('')
#3 /homepages/xx/xxxxxxxxxx/htdocs/xxxxxxxxx-v3_5_2/system/modules/core/classes/Versions.php(689): array_map('StringUtil::bin...', Array)
#4 /homepages/xx/xxxxxxxxxx/htdocs/xxxxxxxxx-v3_5_2/system/modules/core/classes/Versions.php(404): Contao\Versions->implodeRecursive(Array, true)
#5 /homepages/xx/xxxxxxxxxx/htdocs/xxxxxxxxx-v3_5_2/system/modules/core/drivers/DC_Table.php(1763): Contao\Versions->compare()
#6 /homepages/xx/xxxxxxxxxx/htdocs/xxxxxxxxx-v3_5_2/system/modules/core/classes/Backend.php(639): Contao\DC_Table->edit()
#7 /homepages/xx/xxxxxxxxxx/htdocs/xxxxxxxxx-v3_5_2/system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('themes')
#8 /homepages/xx/xxxxxxxxxx/htdocs/xxxxxxxxx-v3_5_2/contao/main.php(20): Contao\BackendMain->run()
#9 {main}
```

**Comment by leofeyer** [comment]
Fixed in 614d2c378876d3fab26b57ede786e2a7fbb9f36c.
