### ISSUE TITLE
Error for registration module if field username doesn't exists

### ISSUE THREAD

**Issue by ufeldmann** [contao/core#8037]
If you create a member registration module and don't want to show the field username, the following error is shown after submitting the form.
I reproduced this error also in the Contao Demo.

```
Fatal error: Uncaught exception Exception with message Query error: Column 'username' cannot be null (INSERT INTO tl_version (pid, tstamp, version, fromTable, username, userid, description, editUrl, active, data) VALUES ('5', '1443167830', 1, 'tl_member', NULL, 0, 'safdsdf sdafsdaf', 'contao/main.php?do=member&act=edit&id=5&rt=1', 1, 'a:37:{s:2:\"id\";s:1:\"5\";s:6:\"tstamp\";s:10:\"1443167830\";s:9:\"firstname\";s:7:\"safdsdf\";s:8:\"lastname\";s:8:\"sdafsdaf\";s:11:\"dateOfBirth\";s:0:\"\";s:6:\"gender\";s:0:\"\";s:7:\"company\";s:7:\"sadfsdf\";s:6:\"street\";s:10:\"sdafasfdsf\";s:6:\"postal\";s:5:\"23223\";s:4:\"city\";s:13:\"fsadfdsfasfda\";s:5:\"state\";s:0:\"\";s:7:\"country\";s:2:\"dk\";s:5:\"phone\";s:0:\"\";s:6:\"mobile\";s:0:\"\";s:3:\"fax\";s:0:\"\";s:5:\"email\";s:15:\"test333@test.de\";s:7:\"website\";s:0:\"\";s:8:\"language\";s:0:\"\";s:6:\"groups\";s:18:\"a:1:{i:0;s:1:\"1\";}\";s:5:\"login\";s:0:\"\";s:8:\"username\";N;s:8:\"password\";s:0:\"\";s:9:\"assignDir\";s:0:\"\";s:7:\"homeDir\";N;s:7:\"disable\";s:1:\"1\";s:5:\"start\";s:0:\"\";s:4:\"stop\";s:0:\"\";s:9:\"dateAdded\";s:10:\"1443167830\";s:9:\"lastLogin\";s:1:\"0\";s:12:\"currentLogin\";s:1:\"0\";s:10:\"loginCount\";s:1:\"3\";s:6:\"locked\";s:1:\"0\";s:7:\"session\";N;s:9:\"autologin\";N;s:9:\"createdOn\";s:1:\"0\";s:10:\"activation\";s:32:\"e74984a85281cf045cade594c6d89a9e\";s:10:\"newsletter\";N;}')) thrown in system/modules/core/library/Contao/Database/Statement.php on line 295
#0 system/modules/core/library/Contao/Database/Statement.php(264): Contao\Database\Statement->query()
#1 system/modules/core/classes/Versions.php(219): Contao\Database\Statement->execute('5', '1443167830', 1, 'tl_member', NULL, 0, 'safdsdf sdafsda...', 'contao/main.php...', 'a:37:{s:2:"id";...')
#2 system/modules/core/classes/Versions.php(135): Contao\Versions->create()
#3 system/modules/core/modules/ModuleRegistration.php(453): Contao\Versions->initialize()
#4 system/modules/core/modules/ModuleRegistration.php(304): Contao\ModuleRegistration->createNewUser(Array)
#5 system/modules/core/modules/Module.php(282): Contao\ModuleRegistration->compile()
#6 system/modules/core/modules/ModuleRegistration.php(58): Contao\Module->generate()
#7 system/modules/core/elements/ContentModule.php(59): Contao\ModuleRegistration->generate()
#8 system/modules/core/library/Contao/Controller.php(476): Contao\ContentModule->generate()
#9 system/modules/core/modules/ModuleArticle.php(213): Contao\Controller::getContentElement(Object(Contao\ContentModel), 'main')
#10 system/modules/core/modules/Module.php(282): Contao\ModuleArticle->compile()
#11 system/modules/core/modules/ModuleArticle.php(67): Contao\Module->generate()
#12 system/modules/core/library/Contao/Controller.php(409): Contao\ModuleArticle->generate(false)
#13 system/modules/core/library/Contao/Controller.php(269): Contao\Controller::getArticle(Object(Contao\ArticleModel), false, false, 'main')
#14 system/modules/core/pages/PageRegular.php(133): Contao\Controller::getFrontendModule('0', 'main')
#15 system/modules/core/controllers/FrontendIndex.php(267): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#16 index.php(20): Contao\FrontendIndex->run()
#17 {main}
```

Steps to reproduce:
1. Create new member registration module
2. Check some fields, that should be shown, but don't mark the field "username"
3. Add module to a page
4. Fill in the form and submit page
5. ERROR ;)

**Comment by leofeyer** [comment]
Fixed in e08833dc18b91d5d0a713ad5db6b5aa7b503de62.
