### ISSUE TITLE
Fatal error: Uncaught exception InvalidArgumentException with message Identifier "event-dispatcher" is not defined. 

### ISSUE THREAD

**Issue by SeoNerd** [contao/core#8095]
I need help !!!! What can I do?

```
Fatal error: Uncaught exception InvalidArgumentException with message Identifier "event-dispatcher" is not defined. thrown in system/modules/pimple-pimple/classes/lib/Pimple.php on line 78

#0 system/modules/metamodels/classes/src/MetaModels/Factory.php(162): Pimple->offsetGet('event-dispatche...')
#1 system/modules/metamodels/classes/src/MetaModels/Factory.php(175): MetaModels\Factory::createDefaultFactory()
#2 system/modules/metamodels/classes/src/MetaModels/Factory.php(213): MetaModels\Factory::getDefaultFactory()
#3 system/modules/metamodels/classes/src/MetaModels/Dca/MetaModelDcaBuilder.php(383): MetaModels\Factory::getAllTables()
#4 system/modules/core/library/Contao/DcaLoader.php(101): MetaModels\Dca\MetaModelDcaBuilder->createDataContainer('tl_session')
#5 system/modules/core/library/Contao/Controller.php(2348): Contao\DcaLoader->load(false)
#6 system/modules/core/library/Contao/DcaExtractor.php(325): Contao\Controller::loadDataContainer('tl_session')
#7 system/modules/core/library/Contao/DcaExtractor.php(120): Contao\DcaExtractor->createExtract()
#8 system/modules/core/library/Contao/Model/QueryBuilder.php(38): Contao\DcaExtractor->__construct('tl_session')
#9 system/modules/core/library/Contao/Model.php(1082): Contao\Model\QueryBuilder::find(Array)
#10 system/modules/core/library/Contao/Model.php(931): Contao\Model::buildFindQuery(Array)
#11 system/modules/core/library/Contao/Model.php(821): Contao\Model::find(Array)
#12 system/modules/core/models/SessionModel.php(49): Contao\Model::findOneBy(Array, Array, Array)
#13 system/modules/core/classes/Frontend.php(501): Contao\SessionModel::findByHashAndName('1ba6b65daf501e6...', 'BE_USER_AUTH')
#14 index.php(51): Contao\Frontend->getLoginStatus('BE_USER_AUTH')
#15 index.php(443): Index->__construct()
#16 {main}
```

**Comment by bytehead** [comment]
Your problem is not a contao core problem. The issue tracker for metamodels is here: https://github.com/MetaModels/core

**Comment by discordier** [comment]
first off, this is related to MetaModels (see the stack trace).
Second, the event dispatcher is not defined in your installation.
What did you do to raise this error? What do you have installed, etc.

Please report the problem (including more details) at above mentioned MetaModels tracker.
