### ISSUE TITLE
Contao 3.2.20 bei mehreren Layouts die eingebunden Module bearbeiten 

### ISSUE THREAD

**Issue by anjuis** [contao/core#8184]
Zerstört  layouts, keine Module oder zu wenige mehr vorhanden, nach dem speichern.

Fehlermeldung im Modulabschnitt des Layouts.

```
Warning: Illegal string offset 'mod' in system/modules/core/widgets/ModuleWizard.php on line 181
#0 system/modules/core/widgets/ModuleWizard.php(181): __error(2, 'Illegal string ...', '/www/htdocs/w01...', 181, Array)
#1 system/modules/core/library/Contao/Widget.php(660): Contao\ModuleWizard->generate()
#2 system/modules/core/templates/backend/be_widget.html5(3): Contao\Widget->generateWithError(true)
#3 system/modules/core/library/Contao/Widget.php(604): include('/www/htdocs/w01...')
#4 system/modules/core/classes/DataContainer.php(480): Contao\Widget->parse()
#5 system/modules/core/drivers/DC_Table.php(2287): Contao\DataContainer->row(Array)
#6 system/modules/core/classes/Backend.php(425): Contao\DC_Table->editAll()
#7 contao/main.php(137): Contao\Backend->getBackendModule('themes')
#8 contao/main.php(288): Main->run()
#9 {main}
```

Erscheint zig mal. Auch in der "mehrere bearbeiten Ansicht"

**Comment by fritzmg** [comment]
3.2.20 is not the most recent contao version. You should update to Contao 3.5.6. Security support for Contao 3.2.20 ended with 2015 » https://contao.org/en/release-plan.html

**Comment by anjuis** [comment]
Thank you for that advice, But i need to stay at 3.2.20 at the moment.

**Comment by fritzmg** [comment]
You should probably use the forum for help: https://community.contao.org/de

**Comment by BugBuster1701** [comment]
Hast du den Punkt "Fehlermeldungen anzeigen" aktiviert? Wenn ja, mach aus.
