### ISSUE TITLE
Zurück Button speichert SubmitOnChange Checkboxen 

### ISSUE THREAD

**Issue by baumannsven** [contao/core#8286]
Wenn man in der Editmaske eine Checkbox aktiviert die per submitOnChange Felder nachlädt und danach auf den Zurück Button oben klickt wird diese gespeichert.
Dies macht dann vor allem Probleme wenn die nachgeladenen Felder als Pflichtfeld deklariert sind.

In der Contao Demo bei den Einstellungen eines Events mit der Checkbox Repeat Events kann man dies nachstellen. Da ist auch der Fall mit dem Pflichtfeld, dass einen Intervall benötigt. Wenn man dies nicht bemerkt und displayErrors aktiviert ist, gibt es einen Warning illegal string offset unit in system/modules/calendar/classes/Events.php on line 251

**Comment by fritzmg** [comment]
`submitOnChange` bedeutet das was es sagt: sobald sich der Wert des Feldes endert, wird das Formular abgeschickt. Dadurch wird auch ein Datenbankeintrag erzeugt bzw. geändert.

**Comment by baumannsven** [comment]
Ist mir schon klar. Aber den Redakteuren nicht. Die klicken auf die Checkbox und danach eventuell auf den Zurück Button.

**Comment by fritzmg** [comment]
Achso, du meinst, wenn man ein bestehendes Event editiert, dort die Checkbox aktiviert aber dann nichts mehr weiter ändert.

**Comment by baumannsven** [comment]
Das hatte ich doch erwähnt

**Comment by fritzmg** [comment]
> Das hatte ich doch erwähnt

Nein, nicht exakt. Das Problem hat man _nur_, wenn man ein _bestehendes_ Event editiert. Nicht aber, wenn man ein neues Event erzeugt und dann auf "Zurück" (oder sonst wo außer "Speichern") klickt.

**Comment by fritzmg** [comment]
## Reproduction steps

1. go to http://demo.contao.org/contao and login
2. go to _Content » Events_ and [edit the calendar entries](http://demo.contao.org/contao/main.php?do=calendar&table=tl_calendar_events&id=3)
3. [create a new event](http://demo.contao.org/contao/main.php?do=calendar&table=tl_calendar_events&id=3&act=create&mode=2&pid=3), fill in the necessary data (do not enable __Repeat event__), enable __Publish event__ and click _Save and close_
4. edit that event again and this time enable __Repeat event__, do not save
5. _optional:_ click on _Go back_
6. open http://demo.contao.org - there will be the following error messages:
```
Warning: Illegal string offset 'unit' in system/modules/calendar/classes/Events.php on line 252

#0 system/modules/calendar/classes/Events.php(252): __error(2, 'Illegal string ...', '...', 252, Array)
#1 system/modules/calendar/classes/Events.php(132): Contao\Events->addEvent(Object(Contao\Model\Collection), '1458601200', '1458687599', 'en/event-detail...', 1458668659, 2145913200, '3')
#2 system/modules/calendar/modules/ModuleEventlist.php(147): Contao\Events->getAllEvents(Array, 1458668659, 2145913200)
#3 system/modules/core/modules/Module.php(283): Contao\ModuleEventlist->compile()
#4 system/modules/calendar/modules/ModuleEventlist.php(70): Contao\Module->generate()
#5 system/modules/core/library/Contao/Controller.php(313): Contao\ModuleEventlist->generate()
#6 system/modules/core/pages/PageRegular.php(133): Contao\Controller::getFrontendModule(Object(Contao\ModuleModel), 'footer')
#7 system/modules/core/controllers/FrontendIndex.php(267): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#8 index.php(20): Contao\FrontendIndex->run()
#9 {main}


Warning: Illegal string offset 'value' in system/modules/calendar/classes/Events.php on line 253

#0 system/modules/calendar/classes/Events.php(253): __error(2, 'Illegal string ...', '...', 253, Array)
#1 system/modules/calendar/classes/Events.php(132): Contao\Events->addEvent(Object(Contao\Model\Collection), '1458601200', '1458687599', 'en/event-detail...', 1458668659, 2145913200, '3')
#2 system/modules/calendar/modules/ModuleEventlist.php(147): Contao\Events->getAllEvents(Array, 1458668659, 2145913200)
#3 system/modules/core/modules/Module.php(283): Contao\ModuleEventlist->compile()
#4 system/modules/calendar/modules/ModuleEventlist.php(70): Contao\Module->generate()
#5 system/modules/core/library/Contao/Controller.php(313): Contao\ModuleEventlist->generate()
#6 system/modules/core/pages/PageRegular.php(133): Contao\Controller::getFrontendModule(Object(Contao\ModuleModel), 'footer')
#7 system/modules/core/controllers/FrontendIndex.php(267): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#8 index.php(20): Contao\FrontendIndex->run()
#9 {main}


Warning: Illegal string offset 'value' in system/modules/calendar/classes/Events.php on line 139

#0 system/modules/calendar/classes/Events.php(139): __error(2, 'Illegal string ...', '...', 139, Array)
#1 system/modules/calendar/modules/ModuleEventlist.php(147): Contao\Events->getAllEvents(Array, 1458668659, 2145913200)
#2 system/modules/core/modules/Module.php(283): Contao\ModuleEventlist->compile()
#3 system/modules/calendar/modules/ModuleEventlist.php(70): Contao\Module->generate()
#4 system/modules/core/library/Contao/Controller.php(313): Contao\ModuleEventlist->generate()
#5 system/modules/core/pages/PageRegular.php(133): Contao\Controller::getFrontendModule(Object(Contao\ModuleModel), 'footer')
#6 system/modules/core/controllers/FrontendIndex.php(267): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#7 index.php(20): Contao\FrontendIndex->run()
#8 {main}
``

**Comment by fritzmg** [comment]
The event modules should probably catch empty intervals for such cases.

**Comment by leofeyer** [comment]
See #8192.

**Comment by fritzmg** [comment]
@leofeyer that issue is independent from this one

**Comment by baumannsven** [comment]
@leofeyer 

Ich habe da eine Idee. Wenn Felder nachgeladen werden, könnte man an den Zurück Button z.B. eine GET Variable hängen. Damit wäre es möglich festzustellen ob so eine Checkbox aktiviert wurde. Danach überprüft man die nachgeladenen Felder auf die Default werde. Wenn diese Werte bestehen setzt man die Checkbox zurück. Was man du dazu?

**Comment by fritzmg** [comment]
@baumannsven the problem occurs whenever there is an empty interval present, not only when you use the "back" button. For instance, the editor could click on __Repeat event__ and then directly go to _Content » Articles_ or another backend section, because he changed his mind and wanted to do something else.

**Comment by asaage** [comment]
thats why i don't like ```submitOnChange``` at all

**Comment by leofeyer** [comment]
Das hat doch nichts mit `submitOnChange` zu tun. Das gleiche kann passieren, wenn man nicht alle Pflichtfelder ausfüllt und dann auf "Zurück" klickt.

**Comment by leofeyer** [comment]
@contao/developers IMHO lässt sich dieses Problem nicht lösen. Was denkt ihr?

**Comment by aschempp** [comment]
Eigentlich dürften wir erst speichern wenn alles erfolgreich ist. Aber so funktioniert `DC_Table` aktuell nicht. Und `DC_Table` umbauen macht imho keinen Sinn, das wäre was für `DC_NG` (next generation)

**Comment by fritzmg** [comment]
It could be solved by always saving apropriate default values according to the Widget. i.e. in this case, `DC_Table` should save `a:2:{s:4:"unit";s:2:"h1";s:5:"value";s:0:"";}` or `a:2:{s:4:"unit";s:0:"";s:5:"value";s:0:"";}` into the field, since the Widget always expects a serialized array in the field.

Or the Widget should always check for valid data.

**Comment by Toflar** [comment]
Das ist einfach Contao. Extensions/Entwickler verlassen sich darauf, dass beim submitOnChange der Wert gespeichert wird. Das können wir nicht einfach ändern, das wäre ein inkompatibler Change.

**Comment by fritzmg** [comment]
Es muss ja nicht geändert werden, dass es gespeichert wird. Es dürfen halt keine ungültigen Daten gespeichert werden.

**Comment by Toflar** [comment]
Wie soll denn das gehen? Eine Checkbox lädt ein Textfeld nach. Das Textfeld ist mandatory. Was soll ich jetzt hier reinspeichern? Default Value ist `''` aber ich will ja das er was eingibt, deswegen ist es ein Pflichtfeld.

**Comment by fritzmg** [comment]
Der Fehler, der dann im Frontend geworfen wird, betrifft ja nicht ein Textfeld, sondern ein `timePeriod` Widget. Bei diesem DCA Feld ist kein default value vorhanden, daher wird im Endeffekt nur der im `sql` definierte default value genommen, der wiederum ein leerere String ist, was aber für ein Widget dieser Art invalid ist.

**Comment by Toflar** [comment]
Wenn es nur um den geht, dann wäre das eine Möglichkeit. Aber das grundsätzliche Problem, dass Pflichtfelder einfach leergelassen werden können, ist damit nicht behoben.

**Comment by fritzmg** [comment]
Ja, das natürlich nicht, aber das kann ja nicht so einfach behoben werden. Aber die von Contao (`DC_Table`) abgespeicherten Werte sollten zumindest valid sein.

Oder wenn man tatsächlich davon ausgehen muss, dass der `DC_Table` irgendwelche ungültigen Strings abspeichert, dann muss an den jeweiligen Stellen wo diese Felder benutzt werden entsprechend auf Gültigkeit überprüft werden. Momentan geht, in diesem Fall bspw., das `calendar` Modul ja davon aus, dass im `repeatEach` Feld immer ein serialisiertes Array mit den indices `value` und `unit` vorkommt.

**Comment by Toflar** [comment]
Das einzig Vernünftige ist da wo `repeatEach` verwendet wird, zu prüfen ob `unit` und `value` vorhanden sind.

**Comment by leofeyer** [comment]
Behoben in 545941d4cd23f04fab9b1e36e59a92913d4ae223. @fritzmg Kannst Du bitte kurz testen, ob das Deinen Testfall behebt?
