### ISSUE TITLE
[3.5.10] - Dateiverwaltung Neuer Ordner anlegen geht nicht

### ISSUE THREAD

**Issue by jonnysp** [contao/core#8316]
Kann keine neuen Ordner in Dateiverwaltung anlegen!

[21-Apr-2016 09:56:27 Europe/Berlin] PHP Fatal error: Uncaught exception 'Exception' with message 'Directory "files/__new__" is not a file' thrown in /www/contao/system/modules/core/library/Contao/File.php on line 134
#0 /www/contao/system/modules/core/drivers/DC_Folder.php(1165): Contao\File->__construct('files/__new__', true)
#1 /www/contao/system/modules/core/classes/Backend.php(650): Contao\DC_Folder->edit()
#2 /www/contao/system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('files')
#3 /www/contao/contao/main.php(20): Contao\BackendMain->run()
#4 {main}

**Comment by bytehead** [comment]
See #8315.
