### ISSUE TITLE
Error in the Backend Template

### ISSUE THREAD

**Issue by LuboTomov** [contao/core#8486]
Hi.
There is an error generated in the error log on the site an some image glitches on the admin panel and on the site.

```
PHP Warning: implode(): Invalid arguments passed in /home/****/public_html/system/modules/core/classes/BackendTemplate.php on line 163
#0 [internal function]: __error(2, 'implode(): Inva...', '/home/****/...', 163, Array)
#1 /home/****/public_html/system/modules/core/classes/BackendTemplate.php(163): implode('","', NULL)
#2 /home/****/public_html/system/modules/core/templates/backend/be_main.html5(43): Contao\BackendTemplate->getDateString()
#3 /home/****/public_html/system/modules/core/library/Contao/BaseTemplate.php(88): include('/home/bicbgqwt/...')
#4 /home/****t/public_html/system/modules/core/library/Contao/Template.php(277): Contao\BaseTemplate->parse()
#5 /home/****/public_html/system/modules/core/classes/BackendTemplate.php(34): Contao\Template->parse()
#6 /home/****/public_html/system/modules/core/classes/BackendTemplate.php(107): Contao\BackendTemplate->parse()
#7 /home/****/public_html/system/modules/core/controllers/BackendMain.php(275): Contao\BackendTemplate->output()
#8 /home/****/public_html/system/modules/core/controllers/BackendMain.php(135): Contao\BackendMain->output()
#9 /home/****/public_html/contao/main.php(20): Contao\BackendMain->run()
#10 {main}
```

**Comment by fritzmg** [comment]
This seems more like a support question, than a bug report. You should use the unofficial Contao forum for that: 

* https://community.contao.org/en/
* https://community.contao.org/de/

It seems your `$GLOBALS['TL_LANG']['DAYS']` array is empty for some reason.

**Comment by xchs** [comment]
> the unofficial Contao forum

@fritzmg I guess you mean the **official** Contao forum, don't you? :smile_cat:

**Comment by fritzmg** [comment]
Hm... yes, for some reason I thought it's considered 'unofficial', my bad ;)
