### ISSUE TITLE
PHP7.1 und cto 3.5.21 - imagemargin

### ISSUE THREAD

**Issue by epsreps** [contao/core#8617]
In ce_text mit image, ce_image und ce_gallery erscheint nachfolgende Fehlermeldung wenn ein "Bildabstand" mit "px" Einheit angegeben wird. Dies tritt nur auf wenn ein margin-left ohne right oder umgekehrt gesetzt ist.

```
Warning: A non-numeric value encountered in system/modules/core/library/Contao/Controller.php on line 1502

#0 system/modules/core/library/Contao/Controller.php(1502): __error(2, 'A non-numeric v...', '/Volumes/...', 1502, Array)
#1 system/modules/core/elements/ContentText.php(72): Contao\Controller::addImageToTemplate(Object(Contao\FrontendTemplate), Array)
#2 system/modules/core/elements/ContentElement.php(265): Contao\ContentText->compile()
#3 system/modules/core/library/Contao/Controller.php(484): Contao\ContentElement->generate()
#4 system/modules/core/modules/ModuleArticle.php(213): Contao\Controller::getContentElement(Object(Contao\ContentModel), 'main')
#5 system/modules/core/modules/Module.php(287): Contao\ModuleArticle->compile()
#6 system/modules/core/modules/ModuleArticle.php(67): Contao\Module->generate()
#7 system/modules/core/library/Contao/Controller.php(417): Contao\ModuleArticle->generate(false)
#8 system/modules/core/library/Contao/Controller.php(277): Contao\Controller::getArticle(Object(Contao\ArticleModel), false, false, 'main')
#9 system/modules/core/pages/PageRegular.php(133): Contao\Controller::getFrontendModule('0', 'main')
#10 system/modules/core/controllers/FrontendIndex.php(285): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#11 index.php(20): Contao\FrontendIndex->run()
#12 {main}
```

**Comment by leofeyer** [comment]
Siehe auch: 0448c4e9488cc7f49d423e6ceeb5478b933c80fc

**Comment by leofeyer** [comment]
Fixed in bc22112b65fc66d812b838e8668c3d599db049f9.
