### ISSUE TITLE
Warning: Division by zero in system/modules/core/library/Contao/Controller.php bei SVG mit Proportionaler Anpassung

### ISSUE THREAD

**Issue by Floxn** [contao/core#8650]
Oben genannte Fehlermeldung erscheint wenn ein SVG proportional angepasst werden soll und nur die Breite in der Bildeinstellung angegeben wird.
In der Demo reproduzierbar:
- SVG Datei hoch laden
- Inhaltselement mit einem Bild erstellen (Bild, Text, Gallerie)
- SVG-Datei auswählen
- Bildgröße "Proportional" auswählen
- Breite einstellen, Höhe leer lassen
- speichern und Schließen
- Fehler erscheint in der Artikelansicht.

Die Ausgabe im Frontend ist richtg, es erscheinen nur die Warnings im Backend.

```
Warning: Division by zero in system/modules/core/library/Contao/Controller.php on line 1519
#0 system/modules/core/library/Contao/Controller.php(1519): __error(2, 'Division by zer...', '/www/htdocs/XXX...', 1519, Array)
#1 system/modules/core/elements/ContentImage.php(69): Contao\Controller::addImageToTemplate(Object(Contao\FrontendTemplate), Array)
#2 system/modules/core/elements/ContentElement.php(265): Contao\ContentImage->compile()
#3 system/modules/core/elements/ContentImage.php(60): Contao\ContentElement->generate()
#4 system/modules/core/library/Contao/Controller.php(484): Contao\ContentImage->generate()
#5 system/modules/core/dca/tl_content.php(1166): Contao\Controller::getContentElement(Object(Contao\ContentModel))
#6 system/modules/core/drivers/DC_Table.php(4284): tl_content->addCteType(Array)
#7 system/modules/core/drivers/DC_Table.php(378): Contao\DC_Table->parentView()
#8 system/modules/core/classes/Backend.php(650): Contao\DC_Table->showAll()
#9 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('article')
#10 contao/main.php(20): Contao\BackendMain->run()
#11 {main}

Warning: Cannot modify header information - headers already sent by (output started at /www/htdocs/XXX/XXX/system/helper/functions.php:65) in system/modules/core/library/Contao/Template.php on line 294
#0 [internal function]: __error(2, 'Cannot modify h...', '/www/htdocs/XXX...', 294, Array)
#1 system/modules/core/library/Contao/Template.php(294): header('Vary: User-Agen...', false)
#2 system/modules/core/classes/BackendTemplate.php(120): Contao\Template->output()
#3 system/modules/core/controllers/BackendMain.php(275): Contao\BackendTemplate->output()
#4 system/modules/core/controllers/BackendMain.php(135): Contao\BackendMain->output()
#5 contao/main.php(20): Contao\BackendMain->run()
#6 {main}

Warning: Cannot modify header information - headers already sent by (output started at /www/htdocs/XXX/XXX/system/helper/functions.php:65) in system/modules/core/library/Contao/Template.php on line 295
#0 [internal function]: __error(2, 'Cannot modify h...', '/www/htdocs/XXX...', 295, Array)
#1 system/modules/core/library/Contao/Template.php(295): header('Content-Type: t...')
#2 system/modules/core/classes/BackendTemplate.php(120): Contao\Template->output()
#3 system/modules/core/controllers/BackendMain.php(275): Contao\BackendTemplate->output()
#4 system/modules/core/controllers/BackendMain.php(135): Contao\BackendMain->output()
#5 contao/main.php(20): Contao\BackendMain->run()
#6 {main}
```

**Comment by leofeyer** [comment]
@ausi /cc

**Comment by ausi** [comment]
Ich konnte den Fehler reproduzieren, er tritt bei mir jedoch nur dann auf, wenn die angegebene Breite über 320 liegt (die `intMaxWidth` im Backend). Ich schau mir das mal genauer an.

**Comment by ausi** [comment]
Sollte mit pull request #8653 behoben werden.

**Comment by leofeyer** [comment]
Danke @ausi.
