### ISSUE TITLE
Grave installation errors with version 4.3.6

### ISSUE THREAD

**Issue by sleitz** [contao/core#8675]
Installing the contao standard-edition or the managed-edition with 4.3.6 (just released) does not work for me.

1. Composer can't run script because the `web/` folder is missing
2. Symfony can't start, because some interfaces are not implemented correctly

Regarding the first:

```bash
[…]
Generating autoload files
> Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication

 // Clearing the cache for the prod environment with debug                      
 // false                                                                       

                                                                                
 [OK] Cache for the "prod" environment (debug=false) was successfully cleared.  
                                                                                


                                              
  [InvalidArgumentException]                  
  The target directory "web" does not exist.  
                                              

assets:install [--symlink] [--relative] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<target>]

Script Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication handling the post-install-cmd event terminated with an exception

                                                                                        
  [RuntimeException]                                                                    
  An error occurred while executing the "assets:install --symlink --relative" command.  
                                                                                        

run-script [--timeout TIMEOUT] [--dev] [--no-dev] [-l|--list] [--] [<script>] [<args>]...
```

I created the `web/` directory by hand and executed the scripts manually.
Regarding the second, this happens when opening the installer after that:

```bash
[22-Mar-2017 15:28:40 Europe/Berlin] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Contao\CoreBundle\Doctrine\Schema\DcaSchemaProvider::__construct() must be an instance of Contao\CoreBundle\Framework\ContaoFrameworkInterface, instance of Symfony\Component\DependencyInjection\ContainerBuilder given, called in /var/www/vhosts/demo11/htdocs/website/vendor/contao/installation-bundle/src/DependencyInjection/ContainerFactory.php on line 174 and defined in /var/www/vhosts/demo11/htdocs/website/vendor/contao/core-bundle/src/Doctrine/Schema/DcaSchemaProvider.php:43
Stack trace:
#0 /var/www/vhosts/demo11/htdocs/website/vendor/contao/installation-bundle/src/DependencyInjection/ContainerFactory.php(174): Contao\CoreBundle\Doctrine\Schema\DcaSchemaProvider->__construct(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#1 /var/www/vhosts/demo11/htdocs/website/vendor/contao/installation-bundle/src/HttpKernel/InstallationKernel.php(109): Contao\InstallationBundle\DependencyInjection\ContainerFactory::create(Object(Contao\InstallationBundle\HttpKernel\ in /var/www/vhosts/demo11/htdocs/website/vendor/contao/core-bundle/src/Doctrine/Schema/DcaSchemaProvider.php on line 43
```

**Comment by sleitz** [comment]
Note: the first issue only affects the managed-edition, the standard-edition completed installation fine. The second error affects both editions.

**Comment by aschempp** [comment]
Did you remove the existing caches?

**Comment by leofeyer** [comment]
Try `/contao/install` instead of `install.php` please.

**Comment by leofeyer** [comment]
See https://github.com/contao/standard-edition/issues/56.
