### ISSUE TITLE
"non-numeric value" bei Galerie mit PHP 7.1

### ISSUE THREAD

**Issue by Funbug** [contao/core#8742]
Vermutlich ähnlich zu #8606

Ich habe den Fehler leider immer noch in einer 3.5.27 mit PHP 7.1:
Warning: A non-numeric value encountered in system/modules/core/elements/ContentGallery.php on line 304

Problem:
\Config::get('maxImageWidth') ist leer.

Mögliche Lösung (int):
$intMaxWidth = (TL_MODE == 'BE') ? floor((640 / $this->perRow)) : floor(((int)\Config::get('maxImageWidth') / $this->perRow));

**Comment by leofeyer** [comment]
Gibt es `$GLOBALS['TL_CONFIG']['maxImageWidth']`-Einträge in Deiner `localconfig.php` oder `default.php`?

**Comment by Funbug** [comment]
Ja, in der localconfig.php steht $GLOBALS['TL_CONFIG']['maxImageWidth'] = '';

**Comment by leofeyer** [comment]
Dann weißt Du ja jetzt, woher der "non-numeric value" kommt.

**Comment by Funbug** [comment]
Ich hab's da nicht reingeschrieben. Aber gut, danke. Problem gelöst. :)

**Comment by fritzmg** [comment]
I can reproduce the issue of `$GLOBALS['TL_CONFIG']['maxImageWidth'] = '';` being written into the `localconfig.php`. Simply do the following:

1. Go to System » Settings » Files and images and set __Maximum front end width__ to a numeric value.
2. Save.
3. Remove the numeric value again (i.e. leave the input field empty).
4. Save.

However, I am not getting the `A non-numeric value` warning in the front end, when adding a content element with an image.

**Comment by Funbug** [comment]
I only had the issue with galleries.

**Comment by fritzmg** [comment]
You are right.

## Reproduction

1. Go to System » Settings » Files and images and set Maximum front end width to a numeric value, then save.
2. Remove the numeric value again (i.e. leave the input field empty), then save.
3. Add a gallery content element.
4. View the page with the gallery in the front end.

The following error will appear:

### Contao 3.5.27
```
Warning: A non-numeric value encountered in system\modules\core\elements\ContentGallery.php on line 304

#0 system\modules\core\elements\ContentGallery.php(304): __error(2, 'A non-numeric v...', 'C:\\xampp\\htdocs...', 304, Array)
#1 system\modules\core\elements\ContentElement.php(265): Contao\ContentGallery->compile()
#2 system\modules\core\elements\ContentGallery.php(76): Contao\ContentElement->generate()
#3 system\modules\core\library\Contao\Controller.php(484): Contao\ContentGallery->generate()
#4 system\modules\core\modules\ModuleArticle.php(213): Contao\Controller::getContentElement(Object(Contao\ContentModel), 'main')
#5 system\modules\core\modules\Module.php(287): Contao\ModuleArticle->compile()
#6 system\modules\core\modules\ModuleArticle.php(67): Contao\Module->generate()
#7 system\modules\core\library\Contao\Controller.php(417): Contao\ModuleArticle->generate(false)
#8 system\modules\core\library\Contao\Controller.php(277): Contao\Controller::getArticle(Object(Contao\ArticleModel), false, false, 'main')
#9 system\modules\core\pages\PageRegular.php(133): Contao\Controller::getFrontendModule('0', 'main')
#10 system\modules\core\controllers\FrontendIndex.php(285): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#11 index.php(20): Contao\FrontendIndex->run()
#12 {main}
```
### Contao 4.4.0
```
Symfony\Component\Debug\Exception\ContextErrorException:
Warning: A non-numeric value encountered

  at vendor\contao\core-bundle\src\Resources\contao\elements\ContentGallery.php:259
  at Contao\ContentGallery->compile()
     (vendor\contao\core-bundle\src\Resources\contao\elements\ContentElement.php:252)
  at Contao\ContentElement->generate()
     (vendor\contao\core-bundle\src\Resources\contao\elements\ContentGallery.php:73)
  at Contao\ContentGallery->generate()
     (vendor\contao\core-bundle\src\Resources\contao\library\Contao\Controller.php:482)
  at Contao\Controller::getContentElement(object(ContentModel), 'main')
     (vendor\contao\core-bundle\src\Resources\contao\modules\ModuleArticle.php:186)
  at Contao\ModuleArticle->compile()
     (vendor\contao\core-bundle\src\Resources\contao\modules\Module.php:227)
  at Contao\Module->generate()
     (vendor\contao\core-bundle\src\Resources\contao\modules\ModuleArticle.php:67)
  at Contao\ModuleArticle->generate(false)
     (vendor\contao\core-bundle\src\Resources\contao\library\Contao\Controller.php:421)
  at Contao\Controller::getArticle(object(ArticleModel), false, false, 'main')
     (vendor\contao\core-bundle\src\Resources\contao\library\Contao\Controller.php:279)
  at Contao\Controller::getFrontendModule('0', 'main')
     (vendor\contao\core-bundle\src\Resources\contao\pages\PageRegular.php:177)
  at Contao\PageRegular->prepare(object(PageModel))
     (vendor\contao\core-bundle\src\Resources\contao\pages\PageRegular.php:49)
  at Contao\PageRegular->getResponse(object(PageModel), true)
     (vendor\contao\core-bundle\src\Resources\contao\controllers\FrontendIndex.php:306)
  at Contao\FrontendIndex->renderPage(object(Collection))
     (vendor\contao\core-bundle\src\Resources\contao\controllers\FrontendIndex.php:78)
  at Contao\FrontendIndex->run()
     (vendor\contao\core-bundle\src\Controller\FrontendController.php:42)
  at Contao\CoreBundle\Controller\FrontendController->indexAction()
  at call_user_func_array(array(object(FrontendController), 'indexAction'), array())
     (vendor\symfony\symfony\src\Symfony\Component\HttpKernel\HttpKernel.php:153)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor\symfony\symfony\src\Symfony\Component\HttpKernel\HttpKernel.php:68)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor\symfony\symfony\src\Symfony\Component\HttpKernel\Kernel.php:171)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (web\app_dev.php:62)
```
## Cause

When removing the input from the `maxImageWidth` field, Contao will write
```php
$GLOBALS['TL_CONFIG']['maxImageWidth'] = '';
```
thus creating a non-numeric value that is later used in a numeric operation. While the DCA field has `'rgxp'=>'natural'` defined in its `eval` section, this still allows empty values, because `'mandatory'=>true` is missing.

So a possible fix could be to simply make the field mandatory, which will disallow users from entering non-numeric values in that field.

**Comment by leofeyer** [comment]
See #8743.
