### ISSUE TITLE
Error with MariaDB 10.2 in Contao 3.5 and 4.4

### ISSUE THREAD

**Issue by hamidabbaszadeh** [contao/core#8753]
There is an error after upgrading MariaDB to version 10.2 when adding "New layout" in both Contao 3.5.* and 4.4.*:

```
Fatal error: Uncaught exception Exception with message Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'rows, cols, sPosition, framework, loadingOrder, modules, mooSource, align, pid, ' at line 1 (INSERT INTO tl_layout (rows, cols, sPosition, framework, loadingOrder, modules, mooSource, align, pid, tstamp) VALUES ('2rwh', '2cll', 'main', 'a:2:{i:0;s:10:\"layout.css\";i:1;s:14:\"responsive.css\";}', 'external_first', 'a:1:{i:0;a:3:{s:3:\"mod\";i:0;s:3:\"col\";s:4:\"main\";s:6:\"enable\";i:1;}}', 'moo_local', 'center', '1', 0)) thrown in system/modules/core/library/Contao/Database/Statement.php on line 295

#0 system/modules/core/library/Contao/Database/Statement.php(264): Contao\Database\Statement->query()
#1 system/modules/core/drivers/DC_Table.php(689): Contao\Database\Statement->execute()
#2 system/modules/core/classes/Backend.php(650): Contao\DC_Table->create()
#3 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('themes')
#4 contao/main.php(20): Contao\BackendMain->run()
#5 {main}
```

**Comment by ausi** [comment]
Related: contao/core-bundle#918
